-- GeoPredIA: DDL opcional para SAP HANA Cloud, ejecutado por un administrador.
-- Seleccionar primero un esquema ESCRIBIBLE DEL EQUIPO en Database Explorer.
-- NO ejecutar en el esquema del dataset oficial. No cambia datos del reto.
-- Este archivo no es una migración del almacenamiento SQLite de la demo.
-- CREATE falla si ya existe una tabla: revisar la versión antes de migrar.
-- Fechas TIMESTAMP en UTC; IDs generados y validados por el backend.

CREATE COLUMN TABLE "GPI_DEVICES" (
  "DEVICE_ID" NVARCHAR(64) PRIMARY KEY,
  "ZONE_ID" NVARCHAR(64) NOT NULL,
  "LABEL" NVARCHAR(150) NOT NULL,
  "ENABLED" BOOLEAN DEFAULT TRUE NOT NULL,
  "CALIBRATION_VERSION" NVARCHAR(100),
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP NOT NULL
);

CREATE COLUMN TABLE "GPI_TELEMETRY" (
  "TELEMETRY_ID" NVARCHAR(64) PRIMARY KEY,
  "DEVICE_ID" NVARCHAR(64) NOT NULL,
  "ZONE_ID" NVARCHAR(64) NOT NULL,
  "OBSERVED_AT" TIMESTAMP NOT NULL,
  "RECEIVED_AT" TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP NOT NULL,
  "SOURCE" NVARCHAR(16) NOT NULL,
  "AIR_TEMPERATURE_C" DECIMAL(7,2),
  "AIR_HUMIDITY_PCT" DECIMAL(5,2),
  "SOIL_MOISTURE_PCT" DECIMAL(5,2),
  "WATER_TEMPERATURE_C" DECIMAL(7,2),
  "CALIBRATION_VERSION" NVARCHAR(100),
  CONSTRAINT "GPI_TELEM_DEVICE_FK" FOREIGN KEY ("DEVICE_ID") REFERENCES "GPI_DEVICES"("DEVICE_ID"),
  CONSTRAINT "GPI_TELEM_SOURCE_CK" CHECK ("SOURCE" IN ('device', 'simulator')),
  CONSTRAINT "GPI_TELEM_AIR_RH_CK" CHECK ("AIR_HUMIDITY_PCT" BETWEEN 0 AND 100),
  CONSTRAINT "GPI_TELEM_SOIL_CK" CHECK ("SOIL_MOISTURE_PCT" BETWEEN 0 AND 100),
  CONSTRAINT "GPI_TELEM_WATER_CK" CHECK ("WATER_TEMPERATURE_C" BETWEEN -55 AND 125),
  CONSTRAINT "GPI_TELEM_UNIQUE" UNIQUE ("DEVICE_ID", "OBSERVED_AT", "SOURCE")
);

CREATE COLUMN TABLE "GPI_EVALUATION_SNAPSHOTS" (
  "EVALUATION_ID" NVARCHAR(64) PRIMARY KEY,
  "ZONE_ID" NVARCHAR(64) NOT NULL,
  "EVALUATED_AT" TIMESTAMP NOT NULL,
  "IMPORTED_AT" TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP NOT NULL,
  "MODEL_VERSION" NVARCHAR(100) NOT NULL,
  "DATASET_VERSION" NVARCHAR(100) NOT NULL,
  "SCENARIO_ID" NVARCHAR(100) DEFAULT 'base' NOT NULL,
  "ORIGIN" NVARCHAR(24) NOT NULL,
  "GEOLOGICAL" DECIMAL(7,4),
  "ENVIRONMENTAL" DECIMAL(7,4),
  "SOCIAL" DECIMAL(7,4),
  "GLOBAL_RISK" DECIMAL(7,4),
  "IMPORTED_BY" NVARCHAR(255) NOT NULL,
  "FILE_SHA256" NVARCHAR(64),
  "EVIDENCE_JSON" NCLOB,
  CONSTRAINT "GPI_EVAL_ORIGIN_CK" CHECK ("ORIGIN" IN ('sac_import', 'demo_synthetic')),
  CONSTRAINT "GPI_EVAL_GEO_CK" CHECK ("GEOLOGICAL" BETWEEN 0 AND 100),
  CONSTRAINT "GPI_EVAL_ENV_CK" CHECK ("ENVIRONMENTAL" BETWEEN 0 AND 100),
  CONSTRAINT "GPI_EVAL_SOC_CK" CHECK ("SOCIAL" BETWEEN 0 AND 100),
  CONSTRAINT "GPI_EVAL_GLOBAL_CK" CHECK ("GLOBAL_RISK" BETWEEN 0 AND 100),
  CONSTRAINT "GPI_EVAL_MISSING_CK" CHECK (
    "GLOBAL_RISK" IS NULL OR
    ("GEOLOGICAL" IS NOT NULL AND "ENVIRONMENTAL" IS NOT NULL AND "SOCIAL" IS NOT NULL)
  )
);

CREATE COLUMN TABLE "GPI_REVIEW_EVENTS" (
  "EVENT_ID" NVARCHAR(64) PRIMARY KEY,
  "EVALUATION_ID" NVARCHAR(64) NOT NULL,
  "WORKFLOW_INSTANCE_ID" NVARCHAR(128) NOT NULL,
  "REVIEWER" NVARCHAR(255) NOT NULL,
  "DECISION" NVARCHAR(16) NOT NULL,
  "JUSTIFICATION" NVARCHAR(5000) NOT NULL,
  "DECIDED_AT" TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP NOT NULL,
  CONSTRAINT "GPI_REVIEW_EVAL_FK" FOREIGN KEY ("EVALUATION_ID") REFERENCES "GPI_EVALUATION_SNAPSHOTS"("EVALUATION_ID"),
  CONSTRAINT "GPI_REVIEW_DECISION_CK" CHECK ("DECISION" IN ('approved', 'observed', 'rejected')),
  CONSTRAINT "GPI_REVIEW_INSTANCE_UQ" UNIQUE ("EVALUATION_ID", "WORKFLOW_INSTANCE_ID")
);

CREATE COLUMN TABLE "GPI_AGENT_REPORTS" (
  "REPORT_ID" NVARCHAR(64) PRIMARY KEY,
  "EVALUATION_ID" NVARCHAR(64) NOT NULL,
  "GENERATED_AT" TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP NOT NULL,
  "MODE" NVARCHAR(32) NOT NULL,
  "AGENT_VERSION" NVARCHAR(100) NOT NULL,
  "REPORT_JSON" NCLOB NOT NULL,
  CONSTRAINT "GPI_AGENT_EVAL_FK" FOREIGN KEY ("EVALUATION_ID") REFERENCES "GPI_EVALUATION_SNAPSHOTS"("EVALUATION_ID")
);

-- Mantener separada la evidencia real y la simulación, también en SAC.
CREATE VIEW "GPI_DEVICE_OBSERVATIONS" AS
SELECT "TELEMETRY_ID", "DEVICE_ID", "ZONE_ID", "OBSERVED_AT", "RECEIVED_AT",
       "AIR_TEMPERATURE_C", "AIR_HUMIDITY_PCT", "SOIL_MOISTURE_PCT",
       "WATER_TEMPERATURE_C", "CALIBRATION_VERSION"
FROM "GPI_TELEMETRY" WHERE "SOURCE" = 'device';

-- Los scores se reciben de SAC. Este esquema NO los calcula con SQL.
-- El servicio debe comprobar además dispositivo/zona, identidad del revisor,
-- idempotencia, límites por sensor y autorización; los CHECK no lo sustituyen.
